recipe/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include
from recipeapp import views as recipe_views
from users import views as user_views
from recipeapp import urls as recipe_urls
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('recipeapp.urls')),
    path('register/',user_views.register,name= 'register'),
    path('login/',authentication_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name= 'logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

recipeapp/urls.py
from django.contrib import admin
from django.urls import path
from recipeapp import views

app_name = 'recipeapp'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('<int:product_id>/',views.detail, name = 'detail'),

    path("add",views.create_item,name='create_item'),
    path("update/<int:id>/",views.update_item,name='update_item'),
    path("delete/<int:id>/",views.delete_item,name='delete_item'),


]

recipeapp/models.py
from unicodedata import category
from django.db import models
# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=200,default='title')
    items = models.TextField(default='ingredient')
    item_ingredients = models.TextField(default='ingredient')
    recipe =models.TextField(default='recipe')
    recipe_aditonal = models.TextField(default='recipe')
    image = models.CharField(max_length = 400,default='image')
    recipe_type = models.CharField(max_length=200,default='food type')
    category = models.CharField(max_length=200,default= 'food type')        

users/models.py
from django.db import models

# Create your models here.

recipeapp/forms.py
from socket import fromshare
from django import forms
from .models import Product

class product_form(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title','items','item_ingredients','recipe','recipe_aditonal','image','recipe_type','category']

users/forms.py
from operator import length_hint
from sys import maxsize
from unittest.util import _MAX_LENGTH
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from phone_field import PhoneField

class Registerform(UserCreationForm):
    email = forms.EmailField()
    contact = forms.IntegerField()


    class Meta:
        model = User
        fields = ['username','email','contact','password1','password2']

recipeapp/views.py
# Create your views here.
from unicodedata import category
from django.shortcuts import render, redirect
from django.http import HttpResponse

from recipeapp.forms import product_form
from .models import Product
from django.core.paginator import Paginator
from django.template import loader
from .forms import product_form
# Create your views here.

def index(request):
    product_objects = Product.objects.all()

#search code

    item_name = request.GET.get('item_name')
    if item_name != '' and item_name is not None:
        product_objects = product_objects.filter(recipe_type=item_name) or product_objects.filter(title=item_name) or product_objects.filter(category=item_name)
    
#paginator code
    paginator = Paginator(product_objects,4)
    page = request.GET.get('page')
    product_objects = paginator.get_page(page)

    return render(request,'index.html',{'product_objects': product_objects})

def detail(request, product_id):
    product = Product.objects.get(pk=product_id)
    context={
        'product':product,
    }
    return render(request,'detail.html',context)

def create_item(request):
    form = product_form(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('recipeapp:index')

    return render(request,'item-form.html',{'form':form})   

def update_item(request,id):
    product = Product.objects.get(id=id)
    form = product_form(request.POST or None, instance=product)

    if form.is_valid():
        form.save()
        return redirect('recipeapp:index')

    return render(request, 'item-form.html',{'form':form,'product':product})    

def delete_item(request,id):
    product_object = Product.objects.get(id=id)

    if request.method == 'POST':
        product_object.delete()
        return redirect('recipeapp:index')

    return render(request,'item-delete.html',{'product_object':product_object})    

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import Registerform
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = Registerform(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'welcome {username}, your account is created')
            return redirect('login')
    else:
        form = Registerform()
    return render(request,'register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request, 'profile.html')

recipeapp/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-6"  style="background-color:rgb(255, 255, 255);">
                <br>
                <br>
                <div class="product_img"><img src="{{product.image}}" alt="{{product.id}}" height="500px" width="500px"></div>
            </div>
            <div class="col-sm-6" >
                <div class="product_title"><h1>{{product.title}}</h1></div>
                <div class="product_recipe_type">{{product.recipe_type}}</div>
                <br>
                <div class="product_items">{{product.items}}</div>
                <br>
                <div class="product_ingredient">{{product.item_ingredients}}</div>
                <br>
                <div class="product_recipe">{{product.recipe}}</div>
                <br>
                <div class="product_recipe_addon">{{product.recipe_aditional}}</div>
                <br>
                {% if user.is_authenticated %}
                    <a href="{% url 'recipeapp:delete_item' product.id %}">delete</a>
                {% endif %}
            </div>
            
            
            
        </div>
    </div>
</body>
</html>

recipeapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <title>Index</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6" style="background-color:rgb(0,0,0);">
                <a href=" ">
                <img  alt="#" src="/static/recipe.png" width="100" height="40">
                </a>
            </div>
            <div class="col-md-4" style="background-color:rgb(0, 0, 0);">
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-danger" href="{% url 'recipeapp:create_item' %}">Create item</a>
                    <button class="btn btn-outline-danger" type="submit">edit item</button>
                    <button class="btn btn-outline-danger" type="submit">view item</button>
                {% endif %} 

            </div>
            <div class="col-md-2" style="background-color:rgb(0, 0, 0) ;">
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-info" href="{% url 'profile' %}">Profile</a>
                    <a class="btn btn-outline-info" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="btn btn-outline-info" href="{% url 'register' %}">Sign up</a>
                    <a class="btn btn-outline-info" href="{% url 'login' %}">Sign in</a>
                {% endif %}   
            </div>
            <div>
            {% if messages %}
                {%for message in messages%}
                <div class="alert alert-{{ message.tag }}">
                    {{ message }}
                </div>
                
                {%endfor%}
            {%endif%}
            </div>
            <div class="col-md-12" >
                <form class="card-card-sm" >
                    <div class="card-body row no-gutter align-items-center">
                        <div class="col" >
                            <input type="search" name="item_name" placeholder="search for products" class="form-control form-control-borderless" >
                        </div>
                        <div class="auto">
                            <button class="btn btn-outline-success" type="submit">search</button>
                        </div>
                    </div>
                </form>
            </div>
        {% for product in product_objects %}
            <div class="col-md-3">
                <div class="card">
                    <a href={{product.id}} style="text-decoration: none;">
                    <img src="{{product.image}}" height='170' class="card-img-top"></a>
                    <div class="card-body">
                        <div class="card-title">
                            <a href={{product.id}} style="text-decoration: none;">
                            {{product.title }}</a>
                        </div>
                        <div class="card-category">
                            <a href={{product.id}} style="text-decoration: none;">{{product.category}} </a>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>

        <div class="row" >
            <div class="col-md-3 offset-md-4" >
                <ul class="pagination" >
                    {% if product_objects.has_previous %}
                        <li class="page-item" >
                            <a class="page-link" href="?page={{ product_objects.previous_page_number }}">   ***previous***   </a>
                        </li>
                    {% endif %}


                    <li class="page-item active" >
                        <a class="page-link" href="?page={{ product_objects.number }}">   ***now***   </a>
                    </li>

                    
                    {% if product_objects.has_next %}
                    <li class="page-item" >
                        <a class="page-link" href="?page={{ product_objects.next_page_number }}">   ***next***   </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        
    </div>
</body>
</html>

recipeapp/templates/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{product.title}}</h2>
    <button type="submit">Confirm</button>
</form>

recipeapp/templates/item-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <title>ITEM-ADD</title>
</head>
<body>
    <div class="container ">
        <div class="row ">
            <div class="col-md-4 offset-md-4 ">
                <div class="card ">
                    <div class="card-header text-white bg-info">
                        <div class="card-title" >
                            ITEM-ADD
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{field}}
                                </div>
                            {% endfor %}    
                            <button class="btn-info" type="submit">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    
    </div>
</body>
</html>

recipeapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <title>LOGIN</title>
</head>
<body>
    <div class="container ">
        <div class="row ">
            <div class="col-md-4 offset-md-4 ">
                <div class="card ">
                    <div class="card-header text-white bg-info">
                        <div class="card-title" >
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{field}}
                                </div>
                            {% endfor %}    
                            <button class="btn-info" type="submit">login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    
    </div>
</body>
</html>

recipeapp/templates/logout.html
<h1>You have been logged out</h1>

recipeapp/templates/profile.html
<h1>{{ user.username }}</h1>

recipeapp/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <title>REGISTER</title>
</head>
<body>
    <div class="container ">
        <div class="row ">
            <div class="col-md-4 offset-md-4 ">
                <div class="card ">
                    <div class="card-header text-white bg-info">
                        <div class="card-title" >
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{field}}
                                </div>
                            {% endfor %}    
                            <button class="btn-info" type="submit">Sign up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    
    </div>
</body>
</html>

users/templates/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">signup</button>
</form>